name: CI

on:
  push: # Will run on all branch pushes
  pull_request: # Will run on all PRs

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: |
        uv sync

    - name: Run ruff linter
      run: |
        uv run ruff check .

    - name: Run ruff formatter
      run: |
        uv run ruff format --check .

    - name: Run mypy type checker
      run: |
        uv run mypy .

    # If ever there are tests to run, uncomment the following lines.
    #
    # - name: Run tests
    #   run: |
    #     uv run pytest --cov --cov-report=term-missing
